import Head from "next/head";
import styled from "styled-components";
import Feed from "../components/Feed";
import Header from "../components/Header";

import LeftSidebar from "../components/LeftSidebar";
import RightSidebar from "../components/RightSidebar";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Social Touch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;1,500&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Header />
      <Container>
        <LeftSidebar />
        <Feed />
        <RightSidebar />
      </Container>
    </div>
  );
}

const Container = styled.div`
  display: flex;
  width: 100%;
  /* overflow: hidden; */
`;
